name: Deploy to S3

on:
  push:
    branches:
      - 'staticSite'  # Trigger the workflow on push to the branch

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_INTERIM_ROLE }}
          aws-region: us-east-1
          role-session-name: GitHub-OIDC-frontend

      # Step 3: Check if there are changes in the current branch
      - name: Check for changes in `staticSite`
        id: changes
        run: |
          git fetch origin staticSite
          git diff --exit-code HEAD -- ./ || echo "Changes detected"
        continue-on-error: true  # Ensure the workflow continues if changes are detected


      # Step 4: Sync files to S3 for static website hosting only if there are changes
      - name: Sync files to S3 if changes detected
        if: steps.changes.outcome == 'failure'  # Only proceed if the previous step found changes
        run: |
          aws s3 sync ./ s3://srophe-syriaca-front-end --delete
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
